<h2>Cadastro de Categoria</h2>
<br/>
<a href="<?php echo $this->url('categoria/default', array('controller' => 'categoria', 'action' => 'index')) ?>" class="btn btn-warning"><i class="glyphicon glyphicon-backward"></i>&nbsp;voltar à lista</a>
<hr/>
<?php
/**
 * @var $form Zend\Form\Form
 */
$form = $this->form;

if ($this->success)
    echo '<div class="alert alert-success">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';
if ($this->error)
    echo '<div class="alert alert-danger">' . $this->error[0] . '<button type="button" class="close" data-dismiss="alert">x</button></div>';

$this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">x</button>')
        ->setMessageCloseString('</div>')
        ->render($form);
$form->setAttribute('action', $this->url('categoria/default', array('controller' => 'categoria', 'action' => 'inserir')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
